modLoader="javafml"
loaderVersion="[51,)"
license="MIT License"
[[mods]]
modId="mobpc"
version="${file.jarVersion}"
displayName="Mob Population Control"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-population-control"
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Mob Population Control Mod'''
[[dependencies.mobpc]]
    modId="forge"
    mandatory=true
    versionRange="[51,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mobpc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
