modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
[[mods]]
modId="mobpc"
version="${file.jarVersion}"
displayName="Mob Population Control"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mob-population-control"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Mob Population Control Mod'''
[[dependencies.mobpc]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mobpc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"
